<Workspace Version="1.3.4.6666" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Closest Level" Description="Return the closest level below the given element." ID="d1760333-ad7e-4e5f-8076-1448b0b7467e" Category="GeniusLoci.Level">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="d255d7aa-7246-4455-b64f-47b9da43769c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="299.4" y="300" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Alban de Chasteigner 2020
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com
#https://github.com/albandechasteigner/GeniusLociForDynamo

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

items = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]
search = []

levels = FilteredElementCollector(doc).OfClass(Level).ToElements()
sortedLevels = sorted(levels,key=lambda level : level.Elevation, reverse=True)

def closest(sortedLevels, number): 
	try:
		result= min([level for level in sortedLevels if level.ProjectElevation &lt;= number], key=lambda x: abs(x.ProjectElevation-number))
	except:
		result= min([level for level in sortedLevels if level.ProjectElevation &gt;= number], key=lambda x: abs(x.ProjectElevation-number))
	return result
	
for item in items:
	if hasattr(item, "Location") :
		loc = item.Location
		if loc:
			# line-based elements (e.g. walls)
			if isinstance(loc,LocationCurve):
				try:elementZ=loc.Curve.Evaluate(0.5, True).Z
				except:elementZ=loc.Curve.Evaluate(0.5, False).Z
			# point-based elements (e.g. most loadable families)
			elif isinstance(loc,LocationPoint):
				elementZ=loc.Point.Z
			elif isinstance(item,Instance):
				elementZ = item.GetTotalTransform().Origin.Z
			elif hasattr(item, "Origin"):
				elementZ = item.Origin.Z
			##Section Marker and ReferenceElevationMarker(Doesn't work for ReferenceElevationMarker)
			elif ElementId(BuiltInCategory.OST_Viewers) == item.Category.Id :
				viewSection = doc.GetElement(ElementId(element.Id.IntegerValue + 1))
				elementZ = viewSection.Origin.Z
			#Elevation Marker
			elif isinstance(item,Autodesk.Revit.DB.ElevationMarker) :
				marker = doc.GetElement(ElementId(item.Id.IntegerValue + 1))
				box=marker.BoundingBox[doc.ActiveView]
				elementZ = ((box.Min+box.Max)/2).Z
			# Grid	
			elif isinstance(item,Autodesk.Revit.DB.Grid):
				elementZ=item.Curve.Evaluate(0.5,True).Z
			# view specific elements (e.g. filled regions)
			elif hasattr(item, "OwnerViewId") and item.OwnerViewId != ElementId.InvalidElementId :
				view=item.Document.GetElement(item.OwnerViewId)
				box = item.BoundingBox[view]
				elementZ = ((box.Min+box.Max)/2).Z
			# sketch-based elements (e.g. floors)
			else :
				box = item.get_BoundingBox(None)
				elementZ = box.Max.Z
		search.append(closest(sortedLevels, elementZ))

OUT = search</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="b91ba998-880e-40fa-a16c-02c2c24757f0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="111" y="300" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="9690f69c-5752-404f-a133-b4e22642db18" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="523.8" y="300" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Level" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d255d7aa-7246-4455-b64f-47b9da43769c" start_index="0" end="9690f69c-5752-404f-a133-b4e22642db18" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b91ba998-880e-40fa-a16c-02c2c24757f0" start_index="0" end="d255d7aa-7246-4455-b64f-47b9da43769c" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>