<Workspace Version="1.3.4.6666" X="-46" Y="6" zoom="1" ScaleFactor="1" Name="Curves FromHatch" Description="Gets the boundaries of the hatches from a CAD link or import.&#xD;&#xA;By Cyril Poupin on the Dynamo Forum" ID="cd997e3a-d190-4728-8d06-19dce5537479" Category="GeniusLoci.CAD Import">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="7013d67f-0815-46ab-a1aa-f771fa98b15a" type="PythonNodeModels.PythonNode" nickname="Python Script" x="401.2" y="292" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#By Cyril Poupin on the Dynamo Forum
#https://forum.dynamobim.com/t/get-face-from-cad-dwg/70043/3

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
import Autodesk.DesignScript.Geometry as DS

clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

importinstance = UnwrapElement(IN[0])

polycurves = []
opt = Options()
geoSet = importinstance.get_Geometry(opt)
for geo in geoSet:
	if isinstance(geo, GeometryInstance):
		for g in  geo.GetInstanceGeometry():
			if isinstance(g, Solid) and g.Volume == 0 :
				for f in g.Faces:
					gstyleName = importinstance.Document.GetElement(f.GraphicsStyleId).GraphicsStyleCategory.Name
					if gstyleName == IN[1] :
						for loopCurve in f.GetEdgesAsCurveLoops():
							ds_polycurv = DS.PolyCurve.ByJoinedCurves(x.ToProtoType() for x in loopCurve)
							polycurves.append(ds_polycurv)
					elif IN[1] == None :
						for loopCurve in f.GetEdgesAsCurveLoops():
							ds_polycurv = DS.PolyCurve.ByJoinedCurves(x.ToProtoType() for x in loopCurve)
							polycurves.append(ds_polycurv)
OUT = polycurves</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="a1db3d49-1bf6-4914-9c72-7cd52d658ea7" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="584.8" y="289.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Curve" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="2b96453c-04a1-4bb9-b273-87caf04d19e1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="206.8" y="275.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="importInstance" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="789c1d45-a971-4c00-ae2c-6c18008dc257" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="96.4" y="352.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Optional input&#xD;&#xA;layerName : var[]..[] = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="7013d67f-0815-46ab-a1aa-f771fa98b15a" start_index="0" end="a1db3d49-1bf6-4914-9c72-7cd52d658ea7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2b96453c-04a1-4bb9-b273-87caf04d19e1" start_index="0" end="7013d67f-0815-46ab-a1aa-f771fa98b15a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="789c1d45-a971-4c00-ae2c-6c18008dc257" start_index="0" end="7013d67f-0815-46ab-a1aa-f771fa98b15a" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>