<Workspace Version="1.3.4.6666" X="-88.908765" Y="83.2020625" zoom="0.70823125" ScaleFactor="1" Name="Element ToSpace" Description="Reports the space of the current or linked model in which the element of the current document is located.&#xD;&#xA;Please note : The custom node maps the element phase to the space phase using the phase name. " ID="a3f4d0c0-12d1-4652-9dbf-eb3eed670dea" Category="GeniusLoci.Room">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="e5f08962-4a05-4b9e-aa33-f08a1cf9d4ab" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="198.915943768367" y="313.528190827502" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Element of current document&#xD;&#xA;element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="eee8b613-16a9-43a5-903d-d9b72ab85e53" type="PythonNodeModels.PythonNode" nickname="Python Script" x="515.69684233063" y="335.365737278584" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Alban de Chasteigner 2021
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com
#https://github.com/albandechasteigner/GeniusLociForDynamo
 
import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
from Revit.Elements import *

doc = DocumentManager.Instance.CurrentDBDocument

Elements = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]
inputdoc = UnwrapElement(IN[1])
spaces=[]

for e in Elements:
	phase = doc.GetElement(e.CreatedPhaseId)
	loc = e.Location
	if type(loc) == LocationPoint:
		pt=loc.Point
	elif type(loc) == LocationCurve:
		pt=loc.Curve.Evaluate(0.5, True)
	# sketch-based elements (ceiling, floor and roof)
	elif isinstance(e, CeilingAndFloor) or isinstance(e,RoofBase) :
		for ref in HostObjectUtils.GetTopFaces(e):
			geomFace=e.GetGeometryObjectFromReference(ref)
			#Get UV BoundingBox
			bbox = geomFace.GetBoundingBox()
			uv=(bbox.Min+bbox.Max)/2
			pt=geomFace.Evaluate(uv)
	if not isinstance(inputdoc, RevitLinkInstance):
		try:
			if isinstance (e, FamilyInstance):
				spaces.append(e.Space[phase].ToDSType(True))
			else: 
				spaces.append(doc.GetSpaceAtPoint(pt,phase).ToDSType(True))
		except:spaces.append(None)
	elif isinstance (inputdoc, RevitLinkInstance):
		try:
			doc2 = inputdoc.GetLinkDocument()
			phaseName = phase.Name
			phase2 = FilteredElementCollector(doc2).OfClass(Phase).ToElements().Find(lambda x : x.Name == phaseName)
			transform = inputdoc.GetTotalTransform()
			locationPoint = transform.Inverse.OfPoint(pt)
			spaces.append(doc2.GetSpaceAtPoint(locationPoint,phase2).ToDSType(True))
		except:spaces.append(None)
	else:spaces.append(None)
	
OUT = spaces</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="7aa22013-b654-42c1-b16f-0f763b1fba0b" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="712.609942886648" y="336.611051402016" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="//Space of current document or linked model&#xD;&#xA;Space" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="2d09c8ad-bcf9-49ff-9690-e6e22b90829a" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="91.4071251445062" y="400.823936390833" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Optional input to retrieve linked spaces&#xD;&#xA;RevitLinksInstance : var[]..[] = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e5f08962-4a05-4b9e-aa33-f08a1cf9d4ab" start_index="0" end="eee8b613-16a9-43a5-903d-d9b72ab85e53" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="eee8b613-16a9-43a5-903d-d9b72ab85e53" start_index="0" end="7aa22013-b654-42c1-b16f-0f763b1fba0b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2d09c8ad-bcf9-49ff-9690-e6e22b90829a" start_index="0" end="eee8b613-16a9-43a5-903d-d9b72ab85e53" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>