<Workspace Version="1.3.4.6666" X="-785.554970344348" Y="29.5223035465719" zoom="0.867977507649016" ScaleFactor="1" Name="FamilyInstance Symbolic Lines" Description="Obtains the symbolic lines of the family instance in the active view.&#xD;&#xA;(For example, the lines and the arcs of a door in a project plan view.)" ID="dd3fd02e-dcc9-4735-8339-5d856fdb8524" Category="GeniusLoci.Family">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="0e692d29-9637-4e48-8e3b-151862168ad1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1046.71391552117" y="226.818642306946" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Alban de Chasteigner 2019
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

items = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]
curveList,outsurfaces,outedges,subCategories=[],[],[],[]

opt = Options()
opt.IncludeNonVisibleObjects = False
opt.View = doc.ActiveView

for item in items:
	geoEle=item.get_Geometry(opt)
	if geoEle != None:
		for geoInstance in geoEle:
			if isinstance(geoInstance, GeometryInstance):
				allCurves,outsurface,outedge,subCategory=[],[],[],[]
				for symbIns in geoInstance.GetInstanceGeometry():
				#for symbIns in geoInstance.SymbolGeometry:
					if isinstance(symbIns, Curve):
						allCurves.append(symbIns.ToProtoType())
						subCategory.append(doc.GetElement(symbIns.GraphicsStyleId).GraphicsStyleCategory.Name)
						#allCurves.append(symbIns.CreateTransformed(geoInstance.Transform).ToProtoType())
					if isinstance(symbIns, Solid) and symbIns.Volume == 0:
						#solid=SolidUtils.CreateTransformed(symbIns,geoInstance.Transform)
						#for face in solid.Faces:
						for face in symbIns.Faces:
							outsurface.extend(face.ToProtoType())
						#for edge in solid.Edges:	
						for edge in symbIns.Edges:
							outedge.append(edge.AsCurve().ToProtoType())
				curveList.append(allCurves)
				subCategories.append(subCategory)
				outsurfaces.append(outsurface)
				outedges.append(outedge)
	else:
		pass	
if isinstance(IN[0], (list)): OUT = curveList,subCategories,outsurfaces, outedges
else: OUT = curveList[0],subCategories[0],outsurfaces[0],outedges[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="18b8309f-6d16-4e84-9483-ab92a4ad3966" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="800.713915521168" y="226.818642306946" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="familyInstance" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="b94a4615-a07c-4c2a-8c7e-3d23321eabc5" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1462.31391552117" y="128.178642306946" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Symbolic Lines" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="f91068f2-cf90-44ff-90c1-3fd8cb159d3c" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1271.11391552117" y="231.03197564028" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];&#xA;x[1];&#xA;x[2];&#xA;x[3];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e9f57572-d459-4c41-b141-bf8136282437" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1462.31391552117" y="211.178642306946" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="SubCategoryName" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="5a29e14f-eb82-4a0d-ba28-4037f627decf" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1462.31391552117" y="295.178642306946" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Surfaces" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="c345102f-8e88-401f-b602-8e703bd05b06" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1462.31391552117" y="378.178642306946" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Edges" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="0e692d29-9637-4e48-8e3b-151862168ad1" start_index="0" end="f91068f2-cf90-44ff-90c1-3fd8cb159d3c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="18b8309f-6d16-4e84-9483-ab92a4ad3966" start_index="0" end="0e692d29-9637-4e48-8e3b-151862168ad1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f91068f2-cf90-44ff-90c1-3fd8cb159d3c" start_index="0" end="b94a4615-a07c-4c2a-8c7e-3d23321eabc5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f91068f2-cf90-44ff-90c1-3fd8cb159d3c" start_index="1" end="e9f57572-d459-4c41-b141-bf8136282437" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f91068f2-cf90-44ff-90c1-3fd8cb159d3c" start_index="2" end="5a29e14f-eb82-4a0d-ba28-4037f627decf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f91068f2-cf90-44ff-90c1-3fd8cb159d3c" start_index="3" end="c345102f-8e88-401f-b602-8e703bd05b06" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>