<Workspace Version="1.3.4.6666" X="-89.8354173404662" Y="75.3631967776531" zoom="0.627408126597635" ScaleFactor="1" Name="Room ToElement" Description="Reports the elements of the current or linked model that are inside the given room of the current document." ID="41469f80-bd49-418a-9aba-cf06e3e3178a" Category="GeniusLoci.Room">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e94d13fe-fdf2-4ca3-978b-f5ccc71571da" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="857.495407829748" y="300.211051402016" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="//Elements of current document or linked model&#xD;&#xA;Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="72275071-b68c-4567-9197-96410543dfd4" type="PythonNodeModels.PythonNode" nickname="Python Script" x="660.58230727373" y="298.965737278584" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Alban de Chasteigner 2021
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com
#https://github.com/albandechasteigner/GeniusLociForDynamo
 
import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

rooms = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]
inputdoc = UnwrapElement(IN[1])
result=[]

if inputdoc is None:
	doc = DocumentManager.Instance.CurrentDBDocument
	transform = Transform.Identity
elif isinstance (inputdoc, RevitLinkInstance):
	doc = inputdoc.GetLinkDocument()
	transform = inputdoc.GetTotalTransform()
for room in rooms:
	elem=[]
	fec = FilteredElementCollector(doc).WhereElementIsNotElementType().WhereElementIsViewIndependent().ToElements().FindAll(lambda x :  type(x.Location) == LocationPoint and x.Category.Id != ElementId(BuiltInCategory.OST_Rooms) or type(x.Location) == LocationCurve or isinstance(x, CeilingAndFloor) or isinstance(x,RoofBase))
	for e in fec:
		loc = e.Location
		if type(loc) == LocationPoint:
			pt=loc.Point
		elif type(loc) == LocationCurve:
			pt=loc.Curve.Evaluate(0.5, False)
		# sketch-based elements (ceiling, floor and roof)
		elif isinstance(e, CeilingAndFloor) or isinstance(e,RoofBase) :
			for ref in HostObjectUtils.GetTopFaces(e):
				geomFace=e.GetGeometryObjectFromReference(ref)
				#Get UV BoundingBox
				bbox = geomFace.GetBoundingBox()
				uv=(bbox.Min+bbox.Max)/2
				pt=geomFace.Evaluate(uv)
		locationPoint = transform.OfPoint(pt)
		if room.IsPointInRoom(locationPoint):
			elem.append(e)
	result.append(elem)
	
if isinstance(IN[0], list): OUT = result
else: OUT = result[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="be4dc284-5b95-4d5d-9a99-0bc2d76c790f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="335.486934387111" y="286.814559805006" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Room of current document&#xD;&#xA;room" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5a451f67-6b43-4732-8b63-94a449899df4" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="195.053108930184" y="374.593725363994" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Optional input to retrieve linked elements&#xD;&#xA;RevitLinksInstance : var[]..[] = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="72275071-b68c-4567-9197-96410543dfd4" start_index="0" end="e94d13fe-fdf2-4ca3-978b-f5ccc71571da" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="be4dc284-5b95-4d5d-9a99-0bc2d76c790f" start_index="0" end="72275071-b68c-4567-9197-96410543dfd4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5a451f67-6b43-4732-8b63-94a449899df4" start_index="0" end="72275071-b68c-4567-9197-96410543dfd4" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>