<Workspace Version="1.3.4.6666" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Show Linked Element" Description="Shows the linked elements by zoom to fit in the current view." ID="36d2fd73-a1c3-4837-ae92-22a24390bfb7" Category="GeniusLoci.Element">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="bab48c96-9463-4de9-84e8-a6ccc531005d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-14.8" y="291.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Linked element&#xD;&#xA;element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="10d0af75-b5a1-4ad4-be97-025623479d93" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="338.8" y="296.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="db01bc38-95e5-41fc-9dfc-106d2c23ab3c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="176.4" y="298" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Inspired by Cyril Poupin
#Alban de Chasteigner 2021
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com
#https://github.com/albandechasteigner/GeniusLociForDynamo

import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference('RevitAPIUI')
from Autodesk.Revit.UI import *

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

uiviews = uidoc.GetOpenUIViews()
view = doc.ActiveView
uiview = [x for x in uiviews if x.ViewId == view.Id][0]

def SumBoxes(boxes):
	minx = min([b.Min.X for b in boxes])
	miny = min([b.Min.Y for b in boxes])
	minz = min([b.Min.Z for b in boxes])
	maxx = max([b.Max.X for b in boxes])
	maxy = max([b.Max.Y for b in boxes])
	maxz = max([b.Max.Z for b in boxes])
	bb = BoundingBoxXYZ()
	bb.Min = XYZ(minx,miny,minz)
	bb.Max = XYZ(maxx,maxy,maxz)
	return bb

elements = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]
bbx=[]

for elem in elements :
	lnkinst=FilteredElementCollector(doc).OfClass(RevitLinkInstance).ToElements().Find(lambda x : x.GetLinkDocument().Title == elem.Document.Title)
	tfLnk = lnkinst.GetTotalTransform()
	if not isinstance(elem,DatumPlane):
		box = elem.get_BoundingBox(None)
		box.Min = tfLnk.OfPoint(box.Min)
		box.Max = tfLnk.OfPoint(box.Max)
	elif isinstance(elem,Grid):
		line=elem.Curve
		start=line.GetEndPoint(0)
		end=line.GetEndPoint(1)    
		box=BoundingBoxXYZ()
		box.Min = tfLnk.OfPoint(start)
		box.Max = tfLnk.OfPoint(end)	
	elif isinstance(elem,ReferencePlane):
		view = doc.ActiveView
		for crv in elem.GetCurvesInView(DatumExtentType.ViewSpecific,view):
			line = crv
		start=line.GetEndPoint(0)
		end=line.GetEndPoint(1)    
		box = BoundingBoxXYZ()
		box.Min = tfLnk.OfPoint(start)
		box.Max = tfLnk.OfPoint(end)	
	bbx.append(box)
	sumBox = SumBoxes(bbx)	
	uiview.ZoomAndCenterRectangle(sumBox.Min, sumBox.Max)

OUT = elements</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="bab48c96-9463-4de9-84e8-a6ccc531005d" start_index="0" end="db01bc38-95e5-41fc-9dfc-106d2c23ab3c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="db01bc38-95e5-41fc-9dfc-106d2c23ab3c" start_index="0" end="10d0af75-b5a1-4ad4-be97-025623479d93" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>