<Workspace Version="1.3.4.6666" X="-255.065749864052" Y="83.8726636657523" zoom="0.568853839275299" ScaleFactor="1" Name="Space ToElement" Description="Reports the elements of the current or linked model that are inside the given space of the current document." ID="10e0e643-2984-4d69-9a69-f20c2036b826" Category="GeniusLoci.Room">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="71a08588-abd7-41cf-9d33-230489ad96a8" type="PythonNodeModels.PythonNode" nickname="Python Script" x="795.812208502652" y="336.675242246554" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Alban de Chasteigner 2021
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com
#https://github.com/albandechasteigner/GeniusLociForDynamo
 
import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

spaces = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]
inputdoc = UnwrapElement(IN[1])
result=[]

if inputdoc is None:
	doc = DocumentManager.Instance.CurrentDBDocument
	transform = Transform.Identity
elif isinstance (inputdoc, RevitLinkInstance):
	doc = inputdoc.GetLinkDocument()
	transform = inputdoc.GetTotalTransform()
for space in spaces:
	elem=[]
	fec = FilteredElementCollector(doc).WhereElementIsNotElementType().WhereElementIsViewIndependent().ToElements().FindAll(lambda x :  type(x.Location) == LocationPoint and x.Category.Id != ElementId(BuiltInCategory.OST_MEPSpaces) or type(x.Location) == LocationCurve or isinstance(x, CeilingAndFloor) or isinstance(x,RoofBase))
	for e in fec:
		loc = e.Location
		if type(loc) == LocationPoint:
			pt=loc.Point
		elif type(loc) == LocationCurve:
			pt=loc.Curve.Evaluate(0.5, False)
		# sketch-based elements (ceiling, floor and roof)
		elif isinstance(e, CeilingAndFloor) or isinstance(e,RoofBase) :
			for ref in HostObjectUtils.GetTopFaces(e):
				geomFace=e.GetGeometryObjectFromReference(ref)
				#Get UV BoundingBox
				bbox = geomFace.GetBoundingBox()
				uv=(bbox.Min+bbox.Max)/2
				pt=geomFace.Evaluate(uv)
		locationPoint = transform.OfPoint(pt)
		if space.IsPointInSpace(locationPoint):
			elem.append(e)
	result.append(elem)
	
if isinstance(IN[0], list): OUT = result
else: OUT = result[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="08765980-dc0b-45c9-884e-26c01428af75" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="963.895407829748" y="335.811051402016" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="//Elements of current document or linked model&#xD;&#xA;Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="71eaddee-8bb5-4378-9386-9f5ed4be10cf" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="442.032283679146" y="317.172457554638" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Space of current document&#xD;&#xA;space" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1900ea67-e520-460e-9bfe-7c048a1b5d3c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="358.93836674762" y="399.890086690536" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Optional input to retrieve linked elements&#xD;&#xA;RevitLinksInstance : var[]..[] = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="71a08588-abd7-41cf-9d33-230489ad96a8" start_index="0" end="08765980-dc0b-45c9-884e-26c01428af75" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="71eaddee-8bb5-4378-9386-9f5ed4be10cf" start_index="0" end="71a08588-abd7-41cf-9d33-230489ad96a8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1900ea67-e520-460e-9bfe-7c048a1b5d3c" start_index="0" end="71a08588-abd7-41cf-9d33-230489ad96a8" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>