<Workspace Version="1.3.4.6666" X="0" Y="0" zoom="1" ScaleFactor="1" Name="View Level" Description="Returns the level to which a view is associated." ID="d096cd55-4824-48e7-9b3e-547bed4b4fc5" Category="GeniusLoci.View">
  <NamespaceResolutionMap>
    <ClassMap partialName="Revit.Application.Document.Current" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Revit.Application.Document" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="28d8e1a0-3605-490a-8c1e-d24cdae8c6b0" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="376.8" y="292" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Level" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="8ace3e7d-5923-4723-bc1b-4f93cea5f9c2" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-362.4" y="294.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="view:var[]..[] = Revit.Application.Document.Current.ActiveView" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="f7dd661b-82b0-4402-b3ef-aee612c866b8" type="PythonNodeModels.PythonNode" nickname="Python Script" x="218.4" y="294.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import View

def GetLevel(view) :
	if hasattr(view, "GenLevel") : return view.GenLevel
	else : return None

views = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [GetLevel(x) for x in views]
else: OUT = GetLevel(views)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="8ace3e7d-5923-4723-bc1b-4f93cea5f9c2" start_index="0" end="f7dd661b-82b0-4402-b3ef-aee612c866b8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f7dd661b-82b0-4402-b3ef-aee612c866b8" start_index="0" end="28d8e1a0-3605-490a-8c1e-d24cdae8c6b0" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>