<Workspace Version="1.3.4.6666" X="26.0556458275593" Y="183.148537929291" zoom="0.712594832628488" ScaleFactor="1" Name="Workset ById" Description="Retrieves the workset by Id." ID="1c20ab1c-b720-46ea-b5c1-9962887e14c2" Category="GeniusLoci.Workset">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="d86a5b50-888e-4184-ab18-75793da330a7" type="PythonNodeModels.PythonNode" nickname="Python Script" x="306.8" y="266.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Alban de Chasteigner 2021
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com
#https://github.com/albandechasteigner/GeniusLociForDynamo

import clr
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import WorksetId

ids = IN[0] if isinstance(IN[0],list) else [IN[0]]
wks, names = [],[]

for worksetId in ids :
	try:
		workset=doc.GetWorksetTable().GetWorkset(WorksetId(worksetId))
		wks.append(workset)
		names.append(workset.Name)
	except:
		wks.append(None)
		names.append(None)
		
if isinstance(IN[0], list): OUT = wks, names
else: OUT = wks[0], names[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="6398a842-66c6-4eae-b754-8ccb90bcc05d" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="476" y="270.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];&#xA;x[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="8cb86ed5-3883-4c8f-93b7-6d924722b465" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="616.172388370788" y="258.675512288501" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Workset" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="327518bb-e034-4ce4-8c14-90f8c086b4be" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="619.648270164411" y="328.526704742234" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="WorksetName" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9beb6f10-9f03-4bc8-91ca-ea83d5bb710a" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="80.8909977519861" y="265.303862927957" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Integer&#xD;&#xA;WorksetId:int[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d86a5b50-888e-4184-ab18-75793da330a7" start_index="0" end="6398a842-66c6-4eae-b754-8ccb90bcc05d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6398a842-66c6-4eae-b754-8ccb90bcc05d" start_index="0" end="8cb86ed5-3883-4c8f-93b7-6d924722b465" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6398a842-66c6-4eae-b754-8ccb90bcc05d" start_index="1" end="327518bb-e034-4ce4-8c14-90f8c086b4be" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9beb6f10-9f03-4bc8-91ca-ea83d5bb710a" start_index="0" end="d86a5b50-888e-4184-ab18-75793da330a7" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>