<Workspace Version="1.3.3.4651" X="258" Y="85" zoom="1" ScaleFactor="1" Name="Document.UnitTypes" Description="Retrieves all available unit types of a given document" ID="7d9a0c46-c83f-4332-a0ed-b57446058633" Category="Clockwork.Revit.Document.Query">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="7cea831a-ed9c-4b2c-aad9-4063deee11ec" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

inputdoc = UnwrapElement(IN[1])
if inputdoc == None:
	doc = DocumentManager.Instance.CurrentDBDocument
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.RevitLinkInstance":
	doc = inputdoc.GetLinkDocument()
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.Document":
	doc = inputdoc
else: doc = None

OUT = doc.GetUnits().GetModifiableUnitTypes()</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="da6c7dc7-2881-4702-9b41-595b6215f3f7" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="toggle : bool = true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="dda25612-d3b4-4718-b65d-f2b4d6caee33" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-215" y="80" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Use only if you want to query a linked model&#xD;&#xA;docOrRevitLinkInstance : var = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="d23d9694-f71a-4d6c-8bd7-36c22a0e349f" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="unitTypes" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="7cea831a-ed9c-4b2c-aad9-4063deee11ec" start_index="0" end="d23d9694-f71a-4d6c-8bd7-36c22a0e349f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="da6c7dc7-2881-4702-9b41-595b6215f3f7" start_index="0" end="7cea831a-ed9c-4b2c-aad9-4063deee11ec" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dda25612-d3b4-4718-b65d-f2b4d6caee33" start_index="0" end="7cea831a-ed9c-4b2c-aad9-4063deee11ec" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>