<Workspace Version="1.3.4.6666" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Document.Enums" Description="Retrieves all Enums from the Revit API" ID="210d5eb1-8d30-4e0b-931b-08b9bcecbc7a" Category="Clockwork.Revit.Document.Query">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="5464962a-ec8c-4dd0-923a-8b4bc61c212d" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="0">
      <Script>import clr
import System
clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')
import Autodesk

rAssembly = [x for x in System.AppDomain.CurrentDomain.GetAssemblies() if x.GetName().Name == 'RevitAPI'][0]
OUT = [x.Name for x in rAssembly.GetTypes() if x.Namespace is not None and x.Namespace.startswith("Autodesk.Revit.") and x.BaseType == System.Enum]
OUT = sorted(OUT, key=str.lower)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="5bbf2974-8cc2-4696-8301-88ef0e5aedf2" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="419" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="enumNames" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="5464962a-ec8c-4dd0-923a-8b4bc61c212d" start_index="0" end="5bbf2974-8cc2-4696-8301-88ef0e5aedf2" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>