<Workspace Version="1.3.4.6666" X="191" Y="273" zoom="1" ScaleFactor="1" Name="Element.AllInstances" Description="Retrieves all instances of a given element" ID="10c454dc-4094-4466-846e-16746ea0b2f3" Category="Clockwork.Revit.Elements.Element.Query">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="e6677cac-8a46-44e8-95b1-a356863cfe53" type="PythonNodeModels.PythonNode" nickname="Python Script" x="425.105715683491" y="40.1610761952759" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import System
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

def GetAllInstances(item):
	collector = FilteredElementCollector(item.Document)
	bic = System.Enum.ToObject(BuiltInCategory, item.Category.Id.IntegerValue)
	collector.OfCategory(bic)
	# This is a workaround
	# because I was too lazy to learn
	# how to implement LINQ in Python
	return [x for x in collector.ToElements() if x.GetTypeId().IntegerValue == item.GetTypeId().IntegerValue]

elements = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [GetAllInstances(x) for x in elements]
else: OUT = GetAllInstances(elements)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="e4c88eec-724c-4052-aef8-4d9cf22cefd9" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="237.105715683491" y="40.1610761952759" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="896e74bc-dec7-4abe-949c-c48718aad496" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="649.105715683492" y="40.1610761952759" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e6677cac-8a46-44e8-95b1-a356863cfe53" start_index="0" end="896e74bc-dec7-4abe-949c-c48718aad496" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e4c88eec-724c-4052-aef8-4d9cf22cefd9" start_index="0" end="e6677cac-8a46-44e8-95b1-a356863cfe53" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>