<Workspace Version="1.3.3.4651" X="210.324237168555" Y="284.456276238536" zoom="1.01204214144457" ScaleFactor="1" Name="Element.CutGeometry" Description="Adds a solid-solid cut for two model elements (if possible). " ID="66f78539-8a80-402e-81dc-28a0737ab127" Category="Clockwork.Revit.Elements.Element.Actions">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="fa79ddac-0e23-48cd-aa6a-9e28ed1fedc0" type="PythonNodeModels.PythonNode" nickname="Python Script" x="498.569683142455" y="72.4293513030842" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from System.Collections.Generic import *
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
items1 = UnwrapElement(IN[0])
items2 = UnwrapElement(IN[1])

def CutGeometry(doc, item1, item2):
	try:
		SolidSolidCutUtils.AddCutBetweenSolids(doc,item1,item2)
		return True
	except:
		try:
			InstanceVoidCutUtils.AddInstanceVoidCut(doc,item1,item2)
			return True
		except: return False

TransactionManager.Instance.EnsureInTransaction(doc)
if isinstance(IN[0], list):
	if isinstance(IN[1], list): OUT = [CutGeometry(doc, x, y) for x, y in zip(items1, items2)]
	else: OUT = [CutGeometry(doc, x, items2) for x in items1]
else:
	if isinstance(IN[1], list): OUT = [CutGeometry(doc, items1, x) for x in items2]
	else: OUT = CutGeometry(doc, items1, items2)
TransactionManager.Instance.TransactionTaskDone()</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c21c0b76-d412-42c8-80d0-87c1b897d41b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="162.569683142455" y="98.9293513030842" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="elementToBeCut: var[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="033818c9-0bdc-4345-9592-605945495201" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="162.569683142455" y="183.429351303084" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="cuttingElement: var[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="1cd28e9e-5f47-490d-8d9c-ffa1dea7a2c6" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="722.569683142455" y="72.4293513030842" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="success" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="53378f01-d0b3-4887-af2f-5df5cf7c998c" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="722.569683142455" y="155.429351303084" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="elementToBeCut" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="db0ca03d-aaeb-4e24-8e2d-ecc7b21b3118" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="722.569683142455" y="238.429351303084" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="cuttingElement" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="fa79ddac-0e23-48cd-aa6a-9e28ed1fedc0" start_index="0" end="1cd28e9e-5f47-490d-8d9c-ffa1dea7a2c6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c21c0b76-d412-42c8-80d0-87c1b897d41b" start_index="0" end="fa79ddac-0e23-48cd-aa6a-9e28ed1fedc0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c21c0b76-d412-42c8-80d0-87c1b897d41b" start_index="0" end="53378f01-d0b3-4887-af2f-5df5cf7c998c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="033818c9-0bdc-4345-9592-605945495201" start_index="0" end="fa79ddac-0e23-48cd-aa6a-9e28ed1fedc0" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="033818c9-0bdc-4345-9592-605945495201" start_index="0" end="db0ca03d-aaeb-4e24-8e2d-ecc7b21b3118" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>