<Workspace Version="1.3.4.6666" X="-58.4698491112185" Y="384.169521482164" zoom="0.867977507649018" ScaleFactor="1" Name="Element.AllViewDependentInstances" Description="Retrieves all instances of a view-dependent element in a given view" ID="93dd587c-c5e0-4072-9fc5-e3b802f20dea" Category="Clockwork.Revit.Elements.Element.Query">
  <NamespaceResolutionMap>
    <ClassMap partialName="View" resolvedName="Revit.Elements.Views.View" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="7156f135-091e-4092-a8f3-94df42ecdfd5" type="PythonNodeModels.PythonNode" nickname="Python Script" x="489.523128476258" y="3.50000000000001" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import System
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

def GetAllInstancesInView(item, view):
	collector = FilteredElementCollector(item.Document)
	bic = System.Enum.ToObject(BuiltInCategory, item.Category.Id.IntegerValue)
	viewfilter = ElementOwnerViewFilter(view.Id)
	collector.WherePasses(viewfilter).OfCategory(bic)
	# This is a workaround
	# because I was too lazy to learn
	# how to implement LINQ in Python
	return [x for x in collector.ToElements() if x.GetTypeId().IntegerValue == item.GetTypeId().IntegerValue]

elements = UnwrapElement(IN[0])
view = UnwrapElement(IN[1])

if isinstance(IN[0], list): OUT = [GetAllInstancesInView(x, view) for x in elements]
else: OUT = GetAllInstancesInView(elements, view)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="ad10938a-72d4-498d-a515-e890750e5278" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="202.523128476258" y="-25.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element : var[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="0457744c-def5-4e2a-84e9-1c86fb9fb5c8" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="202.523128476258" y="58.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="view: var" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="a3b204ee-0668-4be8-952b-aa5c5c4f0897" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="713.523128476258" y="3.50000000000001" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="7156f135-091e-4092-a8f3-94df42ecdfd5" start_index="0" end="a3b204ee-0668-4be8-952b-aa5c5c4f0897" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ad10938a-72d4-498d-a515-e890750e5278" start_index="0" end="7156f135-091e-4092-a8f3-94df42ecdfd5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0457744c-def5-4e2a-84e9-1c86fb9fb5c8" start_index="0" end="7156f135-091e-4092-a8f3-94df42ecdfd5" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>