<Workspace Version="1.3.4.6666" X="127.755805100148" Y="60.9744190281899" zoom="0.70823125" ScaleFactor="1" Name="Element.DependentElements" Description="Returns all elements that, from a logical point of view, are the children of this element. " ID="a1f13bd7-3de3-49bc-ac68-8641e9601273" Category="Clockwork.Revit.Elements.Element.Query">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="938694e9-0470-453e-8ff7-0b45c4507878" type="PythonNodeModels.PythonNode" nickname="Python Script" x="366.75" y="13.1966666666665" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
items = UnwrapElement(IN[0])
version = IN[1]

def GetDependentOld(item):
	# We will need a transaction in order to 
	# temporarily delete the elements and see what dependes on them.
	# Although the new method already exists in 2018.1
	# it requires an element filter up to 2019.0 which to me doesn't make a whole lot of sense
	# (which is probably why they changed that for 2019...).
	TransactionManager.Instance.EnsureInTransaction(doc)
	trans = SubTransaction(doc)
	trans.Start()
	try: dependents = doc.Delete(item.Id)
	except: dependents = []
	trans.RollBack()
	TransactionManager.Instance.TransactionTaskDone()
	return [doc.GetElement(x) for x in dependents if x != item.Id]

def GetDependentNew(item):
	if hasattr(item, "GetDependentElements"): 
		return [doc.GetElement(x) for x in item.GetDependentElements(None) if x != item.Id]
	else: return []
	
if version &lt; 2019:	
	if isinstance(IN[0], list): OUT = [GetDependentOld(x) for x in items]
	else: OUT = GetDependentOld(items)	
else:
	if isinstance(IN[0], list): OUT = [GetDependentNew(x) for x in items]
	else: OUT = GetDependentNew(items)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="29bd15fd-f046-4842-84fa-86d4c3c2a70e" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Application.Version" x="88.75" y="55.1966666666665" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <ID value="3df0961d-9d46-464f-9175-0a74eeb61bc1" />
      <Name value="Application.Version" />
      <Description value="Retrieves the name, version and build of the current Revit application." />
      <Inputs />
      <Outputs>
        <Output value="Name" />
        <Output value="Version" />
        <Output value="Build" />
        <Output value="Language" />
        <Output value="fullVersion" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="da3a6cd0-314f-45ff-8703-832b38c1cae8" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="88.75" y="-28.8033333333335" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element: var[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e3275256-e9d8-409f-b4b6-17c024c8f717" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="590.75" y="13.1966666666665" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="dependents" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="938694e9-0470-453e-8ff7-0b45c4507878" start_index="0" end="e3275256-e9d8-409f-b4b6-17c024c8f717" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="29bd15fd-f046-4842-84fa-86d4c3c2a70e" start_index="1" end="938694e9-0470-453e-8ff7-0b45c4507878" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="da3a6cd0-314f-45ff-8703-832b38c1cae8" start_index="0" end="938694e9-0470-453e-8ff7-0b45c4507878" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>