<Workspace Version="1.3.3.4651" X="162" Y="33" zoom="1" ScaleFactor="1" Name="ElevationMarker.Views" Description="Retrieves all views referenced by a given elevation marker" ID="839239fb-78b4-4758-8e0d-92ddd05053ba" Category="Clockwork.Revit.Elements.ElevationMarker.Query">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="49d67e31-8d16-43ab-ba3d-0d3d790468b7" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

def GetElevationMarkerView(item):
	val = []
	if hasattr(item, "HasElevations"):
		if item.HasElevations():
			for i in range(item.MaximumViewCount):
				view = item.Document.GetElement(item.GetViewId(i))
				if view: val.append(view)
	return val

items = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [GetElevationMarkerView(x) for x in items]
else: OUT = GetElevationMarkerView(items)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="deba8bae-3e94-4ccb-9adf-21d44f63d684" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="elevationMarker" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="c4725bb7-332e-44f2-88ea-fc9d21f0fb0d" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="views" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="49d67e31-8d16-43ab-ba3d-0d3d790468b7" start_index="0" end="c4725bb7-332e-44f2-88ea-fc9d21f0fb0d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="deba8bae-3e94-4ccb-9adf-21d44f63d684" start_index="0" end="49d67e31-8d16-43ab-ba3d-0d3d790468b7" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>