<Workspace Version="1.3.4.6666" X="284.8703696753" Y="285.506010080308" zoom="1.07160593730184" ScaleFactor="1" Name="FamilyInstance.IsMirrored" Description="Checks if a family instance is mirrored" ID="ce7aaa12-ee05-43e7-abfc-412b88a50c87" Category="Clockwork.Revit.Elements.FamilyInstance.Query">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="7d675e6f-ff05-4b4b-89eb-be20b050e79e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="164.643577113644" y="-23.2104700522884" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="familyInstance: var[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="4fc294fd-e0ca-4307-8144-597c5fd12d37" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="724.643577113644" y="-23.2104700522884" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="bool" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="f27486d9-0702-4b28-84ec-72a775b5e9eb" type="PythonNodeModels.PythonNode" nickname="Python Script" x="500.643577113644" y="-23.2104700522884" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

items = UnwrapElement(IN[0])

def IsMirrored(item):
	if hasattr(item, "Mirrored"):
		return item.Mirrored
	else: return False


if isinstance(IN[0], list): OUT = [IsMirrored(x) for x in items]
else: OUT = IsMirrored(items)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="7d675e6f-ff05-4b4b-89eb-be20b050e79e" start_index="0" end="f27486d9-0702-4b28-84ec-72a775b5e9eb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f27486d9-0702-4b28-84ec-72a775b5e9eb" start_index="0" end="4fc294fd-e0ca-4307-8144-597c5fd12d37" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>