<Workspace Version="1.3.4.6666" X="212" Y="87" zoom="1" ScaleFactor="1" Name="Solid.ByUnion+" Description="The OOTB node Solid.ByUnion occasionally fails when trying to merge solids with almost adjacent faces. This node will return the minimum amount of joined solids possible in such cases instead of returning null." ID="4d81b7b4-8bc1-4ff8-8fe5-da74bc37fef0" Category="Clockwork.Geometry.Solid.Create">
  <NamespaceResolutionMap>
    <ClassMap partialName="Autodesk.Solid" resolvedName="Autodesk.DesignScript.Geometry.Solid" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="72eaf7d6-55d8-4984-900e-9d67d35a5723" type="PythonNodeModels.PythonNode" nickname="Python Script" x="276.5" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

solids = IN[0]
OUT = [solids[0]]
solids = solids[1:]

for s in solids:
	i = 0
	unionDone = False
	while i &lt; len(OUT):
		try:
			OUT[i] = OUT[i].Union(s)
			unionDone = True
			break
		except:	i += 1
	if not unionDone: OUT.append(s)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a16037aa-5030-4629-84fd-8d27bd3e5211" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-51.5" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="solids: Autodesk.Solid[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="5fabc3d5-a3f1-4062-ba37-c09f42a9bc08" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="500.5" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="solids" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="72eaf7d6-55d8-4984-900e-9d67d35a5723" start_index="0" end="5fabc3d5-a3f1-4062-ba37-c09f42a9bc08" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a16037aa-5030-4629-84fd-8d27bd3e5211" start_index="0" end="72eaf7d6-55d8-4984-900e-9d67d35a5723" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>