<Workspace Version="1.3.3.4651" X="-41.2388617806726" Y="259.590758652033" zoom="0.827153793170385" ScaleFactor="1" Name="Wall.Flip" Description="Flips the  orientation of a given wall - DO ***NOT*** USE IN AUTOMATIC MODE" ID="2b08b874-ab51-4689-930b-f3e673995359" Category="Clockwork.Revit.Elements.Wall.Actions">
  <NamespaceResolutionMap>
    <ClassMap partialName="Wall" resolvedName="Revit.Elements.Wall" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="41f2d38a-2ef8-40eb-9a9a-3b2c9ed7aa4e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="256.307332293292" y="74.8307332293291" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="wall : Wall[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="0bdbf151-774f-4dd9-b91d-4c8505e86874" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="750.307332293292" y="32.8307332293291" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="wall" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="45d618ef-ea47-4cc3-83ce-1dfe386d6df1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="526.307332293292" y="116.830733229329" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
walls = UnwrapElement(IN[0])

def FlipWall(item):
	if hasattr(item, "Flip"):
		try:
			item.Flip()
			return True
		except: return False
	else: return False

TransactionManager.Instance.EnsureInTransaction(doc)
if isinstance(IN[0], list): OUT = [FlipWall(x) for x in walls]
else: OUT = FlipWall(walls)
TransactionManager.Instance.TransactionTaskDone()</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="6dc8427b-e28a-4cfe-a17b-00c84242e9d2" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="750.307332293292" y="116.830733229329" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="success" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="41f2d38a-2ef8-40eb-9a9a-3b2c9ed7aa4e" start_index="0" end="0bdbf151-774f-4dd9-b91d-4c8505e86874" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="41f2d38a-2ef8-40eb-9a9a-3b2c9ed7aa4e" start_index="0" end="45d618ef-ea47-4cc3-83ce-1dfe386d6df1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="45d618ef-ea47-4cc3-83ce-1dfe386d6df1" start_index="0" end="6dc8427b-e28a-4cfe-a17b-00c84242e9d2" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>